// HTTP face of a long-lived agent session, served from INSIDE the container.
//
// See session-protocol.ts for why the container (not the app) is the durable
// state holder. This module is only transport: it authenticates, arbitrates a
// single attached reader, and long-polls the frame log. All state lives in the
// injected AgentSessionState.
//
// Security boundary: the port is published on 127.0.0.1 only (see
// buildContainerRunArgs) AND every request must carry the per-container Bearer
// secret that was generated by the host and shipped in the --env-file. Two
// independent gates, because a published port is reachable by anything else on
// the host loopback.

import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";

import {
  ATTACH_TOKEN_HEADER,
  type AgentSessionFrameBody,
  type AgentSessionState,
  type SessionExitReason
} from "./session-protocol";

export type AgentSessionServerHandlers = {
  /** Called once, with the job the host posted. */
  onJob: (job: unknown) => void;
  /** Steering message for the live turn. False → host must queue instead. */
  onMessage: (text: string) => boolean;
  onCancel: () => void;
  /** The session is over (host released it, or a TTL fired). */
  onExit: (reason: SessionExitReason) => void;
};

export type AgentSessionServer = {
  /** Append a frame and wake every long-poll waiting on it. */
  emit: (frame: AgentSessionFrameBody) => void;
  listen: (port: number, host?: string) => Promise<number>;
  close: () => Promise<void>;
  /** Address actually bound (useful when port 0 was requested in tests). */
  port: () => number | null;
};

const DEFAULT_POLL_WAIT_MS = 25_000;
const MAX_POLL_WAIT_MS = 60_000;
// Job bodies legitimately carry the document's image blocks as base64 data
// URLs, so a single ordinary selection edit on a screenshot-heavy document is
// several MB. The old 4 MiB ceiling turned that into a hard run failure, and it
// failed in the worst possible way: the socket was destroyed mid-upload, so the
// host's undici fetch surfaced the opaque "fetch failed" (2026-08-12 incident).
const DEFAULT_MAX_BODY_BYTES = 128 * 1024 * 1024;
const MIN_MAX_BODY_BYTES = 4 * 1024 * 1024;

export function resolveMaxSessionBodyBytes(
  env: Record<string, string | undefined> = process.env
): number {
  const raw = Number(env.AGENT_SESSION_MAX_BODY_BYTES);
  if (Number.isFinite(raw) && raw > 0) return Math.max(MIN_MAX_BODY_BYTES, Math.floor(raw));
  return DEFAULT_MAX_BODY_BYTES;
}

export const MAX_SESSION_BODY_BYTES = resolveMaxSessionBodyBytes();

export class SessionBodyTooLargeError extends Error {
  constructor(limitBytes: number) {
    super(`request body exceeds ${limitBytes} bytes (AGENT_SESSION_MAX_BODY_BYTES)`);
    this.name = "SessionBodyTooLargeError";
  }
}

export function createAgentSessionServer(options: {
  state: AgentSessionState;
  secret: string;
  handlers: AgentSessionServerHandlers;
  /** TTL sweep interval; 0 disables the timer (tests drive expiry directly). */
  sweepIntervalMs?: number;
}): AgentSessionServer {
  const { state, secret, handlers } = options;
  const waiters = new Set<() => void>();
  let server: Server | null = null;
  let sweepTimer: NodeJS.Timeout | null = null;

  const wake = () => {
    for (const waiter of [...waiters]) waiter();
  };

  const emit = (frame: AgentSessionFrameBody) => {
    state.append(frame);
    wake();
  };

  const authorized = (req: IncomingMessage) => {
    const header = req.headers.authorization ?? "";
    return header === `Bearer ${secret}`;
  };

  const json = (res: ServerResponse, status: number, body: unknown) => {
    const payload = JSON.stringify(body);
    res.writeHead(status, { "content-type": "application/json", "content-length": Buffer.byteLength(payload) });
    res.end(payload);
  };

  const readBody = (req: IncomingMessage) =>
    new Promise<unknown>((resolve, reject) => {
      let raw = "";
      let oversize = false;
      req.setEncoding("utf8");
      req.on("data", (chunk: string) => {
        if (oversize) return;
        raw += chunk;
        if (raw.length > MAX_SESSION_BODY_BYTES) {
          // Never destroy the socket here: the caller would see a transport
          // error with no status and no reason. Drop what we buffered, drain
          // the rest, and answer with a real 413 once the upload finishes.
          oversize = true;
          raw = "";
        }
      });
      req.on("end", () => {
        if (oversize) {
          reject(new SessionBodyTooLargeError(MAX_SESSION_BODY_BYTES));
          return;
        }
        if (!raw.trim()) {
          resolve({});
          return;
        }
        try {
          resolve(JSON.parse(raw));
        } catch (error) {
          reject(error);
        }
      });
      req.on("error", reject);
    });

  const handle = async (req: IncomingMessage, res: ServerResponse) => {
    if (!authorized(req)) {
      json(res, 401, { error: "unauthorized" });
      return;
    }
    const url = new URL(req.url ?? "/", "http://session.local");
    const method = req.method ?? "GET";

    // /status and /attach are the only endpoints reachable without a current
    // attach token: they are how a new process finds out where things stand and
    // takes over.
    if (method === "GET" && url.pathname === "/status") {
      // `?probe=1` is a pure liveness read and deliberately does NOT count as
      // contact. The reaper probes every sweep; if that reset the no-contact
      // TTL, a container whose owning deployment is gone and which nobody ever
      // adopts would be kept alive forever by the very check meant to notice
      // that nobody is driving it.
      if (url.searchParams.get("probe") !== "1") state.touch();
      json(res, 200, state.status());
      return;
    }
    if (method === "POST" && url.pathname === "/attach") {
      json(res, 200, state.attach());
      return;
    }

    const token = firstHeader(req.headers[ATTACH_TOKEN_HEADER]);
    if (!state.isCurrentToken(token)) {
      // 409 is the signal for "another process took over" — a superseded
      // reader must stop polling rather than compete for the same frames.
      json(res, 409, { error: "attach-superseded", status: state.status() });
      return;
    }
    state.touch();

    if (method === "POST" && url.pathname === "/job") {
      let body: unknown;
      try {
        body = await readBody(req);
      } catch (error) {
        const status = error instanceof SessionBodyTooLargeError ? 413 : 400;
        json(res, status, { error: `invalid job body: ${(error as Error).message}` });
        return;
      }
      const job = (body as { job?: unknown })?.job ?? body;
      const accepted = state.acceptJob(job);
      if (accepted) handlers.onJob(job);
      json(res, 200, { accepted, status: state.status() });
      return;
    }

    if (method === "GET" && url.pathname === "/frames") {
      const since = Number(url.searchParams.get("since") ?? "0");
      const wait = Math.min(MAX_POLL_WAIT_MS, Number(url.searchParams.get("wait") ?? DEFAULT_POLL_WAIT_MS) || 0);
      const first = state.framesSince(since);
      if (first.frames.length > 0 || first.done || wait <= 0) {
        json(res, 200, first);
        return;
      }
      await waitForFrames(waiters, wait, res);
      state.touch();
      json(res, 200, state.framesSince(since));
      return;
    }

    if (method === "POST" && url.pathname === "/message") {
      let body: unknown;
      try {
        body = await readBody(req);
      } catch (error) {
        const status = error instanceof SessionBodyTooLargeError ? 413 : 400;
        json(res, status, { error: `invalid message body: ${(error as Error).message}` });
        return;
      }
      const text = (body as { text?: unknown })?.text;
      if (typeof text !== "string" || !text.trim()) {
        json(res, 400, { error: "text is required" });
        return;
      }
      let delivered = false;
      try {
        delivered = handlers.onMessage(text);
      } catch {
        delivered = false;
      }
      json(res, 200, { delivered });
      return;
    }

    if (method === "POST" && url.pathname === "/cancel") {
      handlers.onCancel();
      json(res, 200, { ok: true });
      return;
    }

    if (method === "POST" && url.pathname === "/release") {
      json(res, 200, { ok: true });
      // Let the response flush before the process tears itself down.
      setTimeout(() => handlers.onExit("released"), 10).unref?.();
      return;
    }

    json(res, 404, { error: "not found" });
  };

  const sweep = () => {
    const reason = state.expiredReason();
    if (reason) handlers.onExit(reason);
  };

  return {
    emit,
    port() {
      const address = server?.address();
      return address && typeof address === "object" ? address.port : null;
    },
    listen(port, host = "0.0.0.0") {
      server = createServer((req, res) => {
        handle(req, res).catch((error) => {
          json(res, 500, { error: error instanceof Error ? error.message : String(error) });
        });
      });
      // A long-poll must not be a keep-alive victim.
      server.keepAliveTimeout = MAX_POLL_WAIT_MS + 30_000;
      server.headersTimeout = MAX_POLL_WAIT_MS + 60_000;
      server.requestTimeout = 0;
      const interval = options.sweepIntervalMs ?? 30_000;
      if (interval > 0) {
        sweepTimer = setInterval(sweep, interval);
        sweepTimer.unref?.();
      }
      return new Promise((resolve, reject) => {
        server!.once("error", reject);
        server!.listen(port, host, () => {
          const address = server!.address();
          resolve(address && typeof address === "object" ? address.port : port);
        });
      });
    },
    async close() {
      if (sweepTimer) clearInterval(sweepTimer);
      wake();
      const current = server;
      server = null;
      if (!current) return;
      // Long polls keep sockets alive for up to keepAliveTimeout (≈90s), and
      // `close()` alone waits for every one of them — the container would sit
      // there long after it was released. We are shutting down: drop them.
      current.closeAllConnections?.();
      await new Promise<void>((resolve) => current.close(() => resolve()));
    }
  };
}

function firstHeader(value: string | string[] | undefined): string | null {
  if (Array.isArray(value)) return value[0] ?? null;
  return value ?? null;
}

function waitForFrames(waiters: Set<() => void>, waitMs: number, res: ServerResponse): Promise<void> {
  return new Promise<void>((resolve) => {
    let settled = false;
    const done = () => {
      if (settled) return;
      settled = true;
      waiters.delete(waiter);
      clearTimeout(timer);
      resolve();
    };
    const waiter = () => done();
    const timer = setTimeout(done, waitMs);
    waiters.add(waiter);
    // A host that walks away mid-poll (deploy, crash) must not leak a waiter.
    res.on("close", done);
  });
}
