#!/usr/bin/env bash
# Blue/green zero-downtime deploy with graceful drain.
#
# Topology:
#   cloudflared -> Caddy on :14141 (load balancer, admin API on :2019)
#              -> app "blue"  on :14142 (dist dir .next-blue)
#              -> app "green" on :14143 (dist dir .next-green)
#
# Each deploy builds the INACTIVE color into its own dist dir (never touching
# the artifacts the live server is serving), starts it, waits for
# /api/health, switches the Caddy upstream, then asks the old process to
# drain: it disconnects its Slack socket, stops claiming scheduled tasks,
# finishes its in-flight agent runs (shared SQLite + Slack Web API keep
# working), and exits on its own.
#
# First run bootstraps: if the legacy single-process server still owns
# :14141, it is killed (one final ~2-5s downtime + one final run
# interruption) so Caddy can take the port.
#
# Usage: ./deploy/deploy.sh
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"

LB_PORT=14141
BLUE_PORT=14142
GREEN_PORT=14143
CADDY_ADMIN="localhost:2019"
STATE_FILE=".deploy-active"      # contains "blue" or "green"
LOCKHASH_FILE=".deploy-lockhash" # sha256 of package-lock.json at last install
CADDY_CONFIG="deploy/caddy.json" # generated by this script (gitignored)

log() { echo "[deploy] $*"; }
fail() { echo "[deploy] ERROR: $*" >&2; exit 1; }

# PIDs listening on a TCP port. lsof is NOT trustworthy on this host: it fails
# to stat a docker netns and silently omits the next-server listeners entirely
# (2026-08-23: a zombie green held :14143, lsof reported nothing, the new green
# died EADDRINUSE, and the health poll switched traffic to the 2-day-old
# zombie). ss reads /proc/net directly and sees them.
# The trailing `|| true` matters: under `set -euo pipefail` a FREE port makes
# grep match nothing → pipeline exit 1 → the $(…) assignment kills the script
# silently (this happened on the first run of this helper).
port_listeners() {
  ss -tlnpH "sport = :$1" 2>/dev/null | grep -o 'pid=[0-9]*' | cut -d= -f2 | sort -u || true
}

# True if $1 is $2 or a descendant of $2 (walks the ppid chain). NOTE: do not
# parse /proc/<pid>/stat positionally — the comm field can contain spaces
# ("next-server (v15.5.20)") and shifts every later field.
pid_has_ancestor() {
  local p=$1 anc=$2
  while [ -n "$p" ] && [ "$p" -gt 1 ] 2>/dev/null; do
    [ "$p" = "$anc" ] && return 0
    p=$(ps -o ppid= -p "$p" 2>/dev/null | tr -d ' ' || true)
  done
  return 1
}

# ---------------------------------------------------------------- single-flight
# Deploys now share ONE build cache (see "build cache" below) as well as one
# pair of ports and one $STATE_FILE, so two at once corrupt the cache and race
# over the same color. 2026-08-31: an agent fired three deploys in 13 minutes
# while diagnosing a failure. Fail fast instead of interleaving.
exec 9>".deploy.lock"
if ! flock -n 9; then
  fail "another deploy is already running (holding .deploy.lock)"
fi

# ---------------------------------------------------------------- env
if [ -f .env ]; then
  set -a
  # shellcheck disable=SC1091
  . ./.env
  set +a
fi
: "${DATABASE_URL:?DATABASE_URL must be set (via .env or environment)}"
: "${SESSION_SECRET:?SESSION_SECRET must be set (via .env or environment)}"

if [ -z "${DEPLOY_SECRET:-}" ]; then
  DEPLOY_SECRET="$(openssl rand -hex 32)"
  printf '\n# Auth for POST /api/admin/drain (blue/green deploys)\nDEPLOY_SECRET=%s\n' "$DEPLOY_SECRET" >> .env
  export DEPLOY_SECRET
  log "generated DEPLOY_SECRET and appended it to .env"
fi

command -v caddy >/dev/null || fail "caddy not found (brew install caddy)"

# ---------------------------------------------------------------- colors
ACTIVE="blue"
if [ -f "$STATE_FILE" ]; then
  ACTIVE="$(cat "$STATE_FILE")"
fi
case "$ACTIVE" in
  blue)  NEW="green"; NEW_PORT=$GREEN_PORT; OLD_PORT=$BLUE_PORT ;;
  green) NEW="blue";  NEW_PORT=$BLUE_PORT;  OLD_PORT=$GREEN_PORT ;;
  *) fail "unexpected active color '$ACTIVE' in $STATE_FILE" ;;
esac
log "active=$ACTIVE -> deploying $NEW on :$NEW_PORT"

# ---------------------------------------------------------------- free target port
# Only ever touch the NEW color's port — never the LB or the active color.
LISTENERS=$(port_listeners "$NEW_PORT")
if [ -n "$LISTENERS" ]; then
  log "killing stale listener(s) on :$NEW_PORT: $LISTENERS"
  # shellcheck disable=SC2086
  kill $LISTENERS 2>/dev/null || true
  sleep 2
  LISTENERS=$(port_listeners "$NEW_PORT")
  # shellcheck disable=SC2086
  [ -n "$LISTENERS" ] && kill -9 $LISTENERS 2>/dev/null || true
  sleep 1
fi
[ -z "$(port_listeners "$NEW_PORT")" ] || fail ":$NEW_PORT still occupied"

# ---------------------------------------------------------------- dependencies
# `npm ci` deletes node_modules, which the LIVE server still requires at
# runtime (next start lazily loads packages per route) — that would be
# downtime through the back door. Use non-destructive `npm install`, and only
# when the lockfile actually changed.
LOCK_HASH="$(shasum -a 256 package-lock.json | awk '{print $1}')"
if [ ! -d node_modules ] || [ "$(cat "$LOCKHASH_FILE" 2>/dev/null || true)" != "$LOCK_HASH" ]; then
  log "package-lock.json changed (or first deploy) — npm install"
  npm install --no-audit --no-fund
  echo "$LOCK_HASH" > "$LOCKHASH_FILE"
else
  log "dependencies unchanged — skipping install"
fi

npx prisma generate

# ---------------------------------------------------------------- database
# Snapshot before any schema change (recoverable bad migration). NOTE: the old
# process keeps serving on the old code while the new schema is live, so
# migrations must be expand/contract: additive in one deploy, destructive
# cleanup only in a later deploy once no old process can be running.
DB_FILE="prisma/dev.db"
if [ -f "$DB_FILE" ]; then
  mkdir -p backups
  BACKUP_FILE="backups/dev_$(date +%Y%m%d_%H%M%S).db"
  log "backing up $DB_FILE -> $BACKUP_FILE"
  # Live server writes constantly; .backup needs a busy timeout or it dies
  # instantly with "database is locked". Retry a few times to ride out any
  # long write transaction.
  BACKUP_OK=""
  for _try in 1 2 3; do
    if sqlite3 -cmd ".timeout 60000" "$DB_FILE" ".backup '$BACKUP_FILE'"; then
      BACKUP_OK=1
      break
    fi
    log "backup attempt $_try failed (database busy), retrying in 5s..."
    rm -f "$BACKUP_FILE"
    sleep 5
  done
  [ -n "$BACKUP_OK" ] || fail "could not back up $DB_FILE (database locked)"
  ls -t backups/dev_*.db 2>/dev/null | tail -n +4 | while read -r OLD_BAK; do
    log "pruning old backup $OLD_BAK"
    rm -f "$OLD_BAK"
  done
fi
npx prisma db push --skip-generate
npm run db:migrate-security

# ---------------------------------------------------------------- build + start
export NEXT_DIST_DIR=".next-$NEW"

log "building into $NEXT_DIST_DIR"
# The default node heap OOMs this build (2026-08-18: SIGABRT "Reached heap
# limit", failed deploy, worked on retry with a bigger heap). Bake it in;
# an explicit NODE_OPTIONS from the caller still wins.
NODE_OPTIONS="${NODE_OPTIONS:---max-old-space-size=8192}" npm run build

mkdir -p logs
APP_LOG="logs/service_${NEW}_$(date +%Y%m%d_%H%M%S).log"
log "starting $NEW on :$NEW_PORT (log: $APP_LOG)"
# 9>&- closes the .deploy.lock fd: a long-lived child inherits it and would
# otherwise hold the single-flight lock for its entire lifetime, making
# every subsequent deploy fail with "another deploy is already running".
PORT=$NEW_PORT NEXT_DIST_DIR=".next-$NEW" nohup npm run start 9>&- > "$APP_LOG" 2>&1 &
NEW_PID=$!
echo "$NEW_PID" > ".service_${NEW}.pid"

log "waiting for http://localhost:$NEW_PORT/api/health ..."
DEADLINE=$(( $(date +%s) + 180 ))
until curl -sf "http://localhost:$NEW_PORT/api/health" >/dev/null 2>&1; do
  kill -0 "$NEW_PID" 2>/dev/null || fail "new server exited during startup — see $APP_LOG"
  [ "$(date +%s)" -lt "$DEADLINE" ] || fail "new server not healthy within 180s — see $APP_LOG"
  sleep 2
done
HEALTH_JSON="$(curl -s "http://localhost:$NEW_PORT/api/health")"
log "$NEW is healthy: $HEALTH_JSON"

# Identity guard: make sure the process ANSWERING the health check is the one
# we just started. Without this, a zombie listener that survived the port-free
# step answers the poll and we switch traffic to a stale build (2026-08-23).
HEALTH_PID="$(echo "$HEALTH_JSON" | grep -o '"pid":[0-9]*' | cut -d: -f2 || true)"
if [ -z "$HEALTH_PID" ]; then
  fail "health response on :$NEW_PORT has no pid field — refusing to switch traffic"
fi
if ! pid_has_ancestor "$HEALTH_PID" "$NEW_PID"; then
  fail "health on :$NEW_PORT answered by pid $HEALTH_PID, which is not a descendant of the new process $NEW_PID — stale listener? See $APP_LOG"
fi

# ---------------------------------------------------------------- caddy config
write_caddy_config() {
  local upstream_port=$1
  cat > "$CADDY_CONFIG" <<EOF
{
  "admin": { "listen": "$CADDY_ADMIN" },
  "apps": {
    "http": {
      "servers": {
        "gdocs": {
          "listen": [":$LB_PORT"],
          "routes": [
            {
              "handle": [
                {
                  "handler": "reverse_proxy",
                  "flush_interval": -1,
                  "upstreams": [{ "dial": "localhost:$upstream_port" }]
                }
              ]
            }
          ]
        }
      }
    }
  }
}
EOF
}

caddy_running() {
  curl -sf "http://$CADDY_ADMIN/config/" >/dev/null 2>&1
}

# ---------------------------------------------------------------- switch traffic
if caddy_running; then
  log "switching Caddy upstream -> localhost:$NEW_PORT"
  curl -sf -X PATCH -H "Content-Type: application/json" \
    "http://$CADDY_ADMIN/config/apps/http/servers/gdocs/routes/0/handle/0/upstreams" \
    -d "[{\"dial\":\"localhost:$NEW_PORT\"}]" >/dev/null \
    || fail "Caddy upstream switch failed"
  # Keep the on-disk config in sync so a Caddy restart converges on the new color.
  write_caddy_config "$NEW_PORT"
else
  # Bootstrap: no LB yet. If the legacy single-process server owns :$LB_PORT,
  # evict it (final hard restart — its runs die once; the new process's
  # silence reaper will fail them after ~15min).
  log "no Caddy admin API — bootstrapping load balancer on :$LB_PORT"
  LB_HOLDERS=$(port_listeners "$LB_PORT")
  if [ -n "$LB_HOLDERS" ]; then
    log "killing legacy server on :$LB_PORT: $LB_HOLDERS (one final interruption)"
    # shellcheck disable=SC2086
    kill $LB_HOLDERS 2>/dev/null || true
    sleep 2
    LB_HOLDERS=$(port_listeners "$LB_PORT")
    # shellcheck disable=SC2086
    [ -n "$LB_HOLDERS" ] && kill -9 $LB_HOLDERS 2>/dev/null || true
    sleep 1
    # Also reap SIGTERM survivors still holding established server-side sockets
    # (the orphaned-next-server failure mode; see legacy-single-process.sh).
    STALE=$(ss -tnpH state established "( sport = :$LB_PORT )" 2>/dev/null | grep -o 'pid=[0-9]*' | cut -d= -f2 | sort -u || true)
    # shellcheck disable=SC2086
    [ -n "$STALE" ] && kill -9 $STALE 2>/dev/null || true
  fi
  write_caddy_config "$NEW_PORT"
  CADDY_LOG="logs/caddy_$(date +%Y%m%d_%H%M%S).log"
  nohup caddy run --config "$CADDY_CONFIG" 9>&- > "$CADDY_LOG" 2>&1 &
  echo $! > .lb.pid
  log "started Caddy (log: $CADDY_LOG)"
  DEADLINE=$(( $(date +%s) + 30 ))
  until curl -sf "http://localhost:$LB_PORT/api/health" >/dev/null 2>&1; do
    [ "$(date +%s)" -lt "$DEADLINE" ] || fail "LB not serving within 30s — see $CADDY_LOG"
    sleep 1
  done
fi

echo "$NEW" > "$STATE_FILE"
log "traffic now on $NEW: $(curl -s "http://localhost:$LB_PORT/api/health")"

# ---------------------------------------------------------------- drain old
if [ -n "$(port_listeners "$OLD_PORT")" ]; then
  log "asking old process on :$OLD_PORT to drain"
  if curl -sf -X POST -H "Authorization: Bearer $DEPLOY_SECRET" \
      "http://localhost:$OLD_PORT/api/admin/drain"; then
    echo
    log "old process is draining; it will exit once its in-flight runs finish"
  else
    echo
    log "WARNING: drain request failed (old build without the endpoint?)."
    log "         Old process on :$OLD_PORT keeps running — stop it manually once idle:"
    log "         kill \$(ss -tlnpH 'sport = :$OLD_PORT' | grep -o 'pid=[0-9]*' | cut -d= -f2 | sort -u)"
  fi
fi

log "done. LB :$LB_PORT -> $NEW :$NEW_PORT ($NEXT_DIST_DIR)"
