#!/usr/bin/env bash
# Blue/green zero-downtime deploy with graceful drain.
#
# Topology:
#   cloudflared -> Caddy on :14141 (load balancer, admin API on :2019)
#              -> app "blue"  on :14142 (dist dir .next-blue)
#              -> app "green" on :14143 (dist dir .next-green)
#
# Each deploy builds the INACTIVE color into its own dist dir (never touching
# the artifacts the live server is serving), starts it, waits for
# /api/health, switches the Caddy upstream, then asks the old process to
# drain: it disconnects its Slack socket, stops claiming scheduled tasks,
# finishes its in-flight agent runs (shared SQLite + Slack Web API keep
# working), and exits on its own.
#
# First run bootstraps: if the legacy single-process server still owns
# :14141, it is killed (one final ~2-5s downtime + one final run
# interruption) so Caddy can take the port.
#
# Usage: ./deploy/deploy.sh
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"

LB_PORT=14141
BLUE_PORT=14142
GREEN_PORT=14143
CADDY_ADMIN="localhost:2019"
STATE_FILE=".deploy-active"      # contains "blue" or "green"
LOCKHASH_FILE=".deploy-lockhash" # sha256 of package-lock.json at last install
CADDY_CONFIG="deploy/caddy.json" # generated by this script (gitignored)

log() { echo "[deploy] $*"; }
fail() { echo "[deploy] ERROR: $*" >&2; exit 1; }

# ---------------------------------------------------------------- env
if [ -f .env ]; then
  set -a
  # shellcheck disable=SC1091
  . ./.env
  set +a
fi
: "${DATABASE_URL:?DATABASE_URL must be set (via .env or environment)}"
: "${SESSION_SECRET:?SESSION_SECRET must be set (via .env or environment)}"

if [ -z "${DEPLOY_SECRET:-}" ]; then
  DEPLOY_SECRET="$(openssl rand -hex 32)"
  printf '\n# Auth for POST /api/admin/drain (blue/green deploys)\nDEPLOY_SECRET=%s\n' "$DEPLOY_SECRET" >> .env
  export DEPLOY_SECRET
  log "generated DEPLOY_SECRET and appended it to .env"
fi

command -v caddy >/dev/null || fail "caddy not found (brew install caddy)"

# ---------------------------------------------------------------- colors
ACTIVE="blue"
if [ -f "$STATE_FILE" ]; then
  ACTIVE="$(cat "$STATE_FILE")"
fi
case "$ACTIVE" in
  blue)  NEW="green"; NEW_PORT=$GREEN_PORT; OLD_PORT=$BLUE_PORT ;;
  green) NEW="blue";  NEW_PORT=$BLUE_PORT;  OLD_PORT=$GREEN_PORT ;;
  *) fail "unexpected active color '$ACTIVE' in $STATE_FILE" ;;
esac
log "active=$ACTIVE -> deploying $NEW on :$NEW_PORT"

# ---------------------------------------------------------------- free target port
# Only ever touch the NEW color's port — never the LB or the active color.
LISTENERS=$(lsof -tiTCP:"$NEW_PORT" -sTCP:LISTEN 2>/dev/null || true)
if [ -n "$LISTENERS" ]; then
  log "killing stale listener(s) on :$NEW_PORT: $LISTENERS"
  # shellcheck disable=SC2086
  kill $LISTENERS 2>/dev/null || true
  sleep 2
  LISTENERS=$(lsof -tiTCP:"$NEW_PORT" -sTCP:LISTEN 2>/dev/null || true)
  # shellcheck disable=SC2086
  [ -n "$LISTENERS" ] && kill -9 $LISTENERS 2>/dev/null || true
  sleep 1
fi
[ -z "$(lsof -tiTCP:"$NEW_PORT" -sTCP:LISTEN 2>/dev/null || true)" ] || fail ":$NEW_PORT still occupied"

# ---------------------------------------------------------------- dependencies
# `npm ci` deletes node_modules, which the LIVE server still requires at
# runtime (next start lazily loads packages per route) — that would be
# downtime through the back door. Use non-destructive `npm install`, and only
# when the lockfile actually changed.
LOCK_HASH="$(shasum -a 256 package-lock.json | awk '{print $1}')"
if [ ! -d node_modules ] || [ "$(cat "$LOCKHASH_FILE" 2>/dev/null || true)" != "$LOCK_HASH" ]; then
  log "package-lock.json changed (or first deploy) — npm install"
  npm install --no-audit --no-fund
  echo "$LOCK_HASH" > "$LOCKHASH_FILE"
else
  log "dependencies unchanged — skipping install"
fi

npx prisma generate

# ---------------------------------------------------------------- database
# Snapshot before any schema change (recoverable bad migration). NOTE: the old
# process keeps serving on the old code while the new schema is live, so
# migrations must be expand/contract: additive in one deploy, destructive
# cleanup only in a later deploy once no old process can be running.
DB_FILE="prisma/dev.db"
if [ -f "$DB_FILE" ]; then
  mkdir -p backups
  BACKUP_FILE="backups/dev_$(date +%Y%m%d_%H%M%S).db"
  log "backing up $DB_FILE -> $BACKUP_FILE"
  # Live server writes constantly; .backup needs a busy timeout or it dies
  # instantly with "database is locked". Retry a few times to ride out any
  # long write transaction.
  BACKUP_OK=""
  for _try in 1 2 3; do
    if sqlite3 -cmd ".timeout 60000" "$DB_FILE" ".backup '$BACKUP_FILE'"; then
      BACKUP_OK=1
      break
    fi
    log "backup attempt $_try failed (database busy), retrying in 5s..."
    rm -f "$BACKUP_FILE"
    sleep 5
  done
  [ -n "$BACKUP_OK" ] || fail "could not back up $DB_FILE (database locked)"
  ls -t backups/dev_*.db 2>/dev/null | tail -n +4 | while read -r OLD_BAK; do
    log "pruning old backup $OLD_BAK"
    rm -f "$OLD_BAK"
  done
fi
npx prisma db push --skip-generate
npm run db:migrate-security

# ---------------------------------------------------------------- build + start
export NEXT_DIST_DIR=".next-$NEW"
log "building into $NEXT_DIST_DIR"
npm run build

mkdir -p logs
APP_LOG="logs/service_${NEW}_$(date +%Y%m%d_%H%M%S).log"
log "starting $NEW on :$NEW_PORT (log: $APP_LOG)"
PORT=$NEW_PORT NEXT_DIST_DIR=".next-$NEW" nohup npm run start > "$APP_LOG" 2>&1 &
NEW_PID=$!
echo "$NEW_PID" > ".service_${NEW}.pid"

log "waiting for http://localhost:$NEW_PORT/api/health ..."
DEADLINE=$(( $(date +%s) + 180 ))
until curl -sf "http://localhost:$NEW_PORT/api/health" >/dev/null 2>&1; do
  kill -0 "$NEW_PID" 2>/dev/null || fail "new server exited during startup — see $APP_LOG"
  [ "$(date +%s)" -lt "$DEADLINE" ] || fail "new server not healthy within 180s — see $APP_LOG"
  sleep 2
done
log "$NEW is healthy: $(curl -s "http://localhost:$NEW_PORT/api/health")"

# ---------------------------------------------------------------- caddy config
write_caddy_config() {
  local upstream_port=$1
  cat > "$CADDY_CONFIG" <<EOF
{
  "admin": { "listen": "$CADDY_ADMIN" },
  "apps": {
    "http": {
      "servers": {
        "gdocs": {
          "listen": [":$LB_PORT"],
          "routes": [
            {
              "handle": [
                {
                  "handler": "reverse_proxy",
                  "flush_interval": -1,
                  "upstreams": [{ "dial": "localhost:$upstream_port" }]
                }
              ]
            }
          ]
        }
      }
    }
  }
}
EOF
}

caddy_running() {
  curl -sf "http://$CADDY_ADMIN/config/" >/dev/null 2>&1
}

# ---------------------------------------------------------------- switch traffic
if caddy_running; then
  log "switching Caddy upstream -> localhost:$NEW_PORT"
  curl -sf -X PATCH -H "Content-Type: application/json" \
    "http://$CADDY_ADMIN/config/apps/http/servers/gdocs/routes/0/handle/0/upstreams" \
    -d "[{\"dial\":\"localhost:$NEW_PORT\"}]" >/dev/null \
    || fail "Caddy upstream switch failed"
  # Keep the on-disk config in sync so a Caddy restart converges on the new color.
  write_caddy_config "$NEW_PORT"
else
  # Bootstrap: no LB yet. If the legacy single-process server owns :$LB_PORT,
  # evict it (final hard restart — its runs die once; the new process's
  # silence reaper will fail them after ~15min).
  log "no Caddy admin API — bootstrapping load balancer on :$LB_PORT"
  LB_HOLDERS=$(lsof -tiTCP:"$LB_PORT" -sTCP:LISTEN 2>/dev/null || true)
  if [ -n "$LB_HOLDERS" ]; then
    log "killing legacy server on :$LB_PORT: $LB_HOLDERS (one final interruption)"
    # shellcheck disable=SC2086
    kill $LB_HOLDERS 2>/dev/null || true
    sleep 2
    LB_HOLDERS=$(lsof -tiTCP:"$LB_PORT" -sTCP:LISTEN 2>/dev/null || true)
    # shellcheck disable=SC2086
    [ -n "$LB_HOLDERS" ] && kill -9 $LB_HOLDERS 2>/dev/null || true
    sleep 1
    # Also reap SIGTERM survivors still holding established server-side sockets
    # (the orphaned-next-server failure mode; see gdocs-ai.sh).
    STALE=$(lsof -nP -iTCP:"$LB_PORT" -sTCP:ESTABLISHED 2>/dev/null | awk -v pat=":$LB_PORT->" 'NR>1 && index($9, pat) > 0 {print $2}' | sort -u || true)
    # shellcheck disable=SC2086
    [ -n "$STALE" ] && kill -9 $STALE 2>/dev/null || true
  fi
  write_caddy_config "$NEW_PORT"
  CADDY_LOG="logs/caddy_$(date +%Y%m%d_%H%M%S).log"
  nohup caddy run --config "$CADDY_CONFIG" > "$CADDY_LOG" 2>&1 &
  echo $! > .lb.pid
  log "started Caddy (log: $CADDY_LOG)"
  DEADLINE=$(( $(date +%s) + 30 ))
  until curl -sf "http://localhost:$LB_PORT/api/health" >/dev/null 2>&1; do
    [ "$(date +%s)" -lt "$DEADLINE" ] || fail "LB not serving within 30s — see $CADDY_LOG"
    sleep 1
  done
fi

echo "$NEW" > "$STATE_FILE"
log "traffic now on $NEW: $(curl -s "http://localhost:$LB_PORT/api/health")"

# ---------------------------------------------------------------- drain old
if [ -n "$(lsof -tiTCP:"$OLD_PORT" -sTCP:LISTEN 2>/dev/null || true)" ]; then
  log "asking old process on :$OLD_PORT to drain"
  if curl -sf -X POST -H "Authorization: Bearer $DEPLOY_SECRET" \
      "http://localhost:$OLD_PORT/api/admin/drain"; then
    echo
    log "old process is draining; it will exit once its in-flight runs finish"
  else
    echo
    log "WARNING: drain request failed (old build without the endpoint?)."
    log "         Old process on :$OLD_PORT keeps running — stop it manually once idle:"
    log "         kill \$(lsof -tiTCP:$OLD_PORT -sTCP:LISTEN)"
  fi
fi

log "done. LB :$LB_PORT -> $NEW :$NEW_PORT ($NEXT_DIST_DIR)"
