#!/usr/bin/env bash
# Refresh the dev instance's data from production (host side, run by deploy.sh).
#
# dev.nielsrolf.com is r-docs running INSIDE the durable app container of the
# #rdocs-dev channel workspace (see dev/run-dev.sh and CLAUDE.md "Dev instance").
# It never touches production: it gets a scrubbed COPY of the prod SQLite file
# under <workspace>/dev-data/, written here on the host, so nothing inside the
# container can reach — let alone delete — the real database or its secrets.
#
#   - rdocs.db   copy of prisma/dev.db with every secret table wiped + VACUUM
#   - .env       generated ONCE (fresh random keys, no Slack/host credentials);
#                kept across refreshes so dev logins and dev-added credentials survive
#
# Config (from .env or the environment):
#   DEV_WORKSPACE_DOCUMENT_ID  document whose workspace hosts dev (default: #rdocs-dev)
#   DEV_WORKSPACE_DIR          override the workspace checkout path
set -euo pipefail
cd "$(dirname "$0")/.."

log() { echo "[refresh-dev-data] $*"; }

if [ -f .env ]; then set -a; . ./.env; set +a; fi
DEV_DOC="${DEV_WORKSPACE_DOCUMENT_ID:-cmrtjzahr0003c3tnabv91vqh}"
WS="${DEV_WORKSPACE_DIR:-.research-workspaces/$DEV_DOC/rdocs}"
DB_FILE="${DB_FILE:-prisma/dev.db}"

if [ ! -d "$WS/.git" ]; then
  log "workspace $WS is not a git checkout yet (link the channel to nielsrolf/rdocs and run one agent session); skipping"
  exit 0
fi
[ -f "$DB_FILE" ] || { log "no database at $DB_FILE"; exit 1; }

OUT="$WS/dev-data"
mkdir -p "$OUT"
# Self-ignoring: agent runs `git add -A` in this checkout; a 3 GB DB must never
# be committed even if the checkout predates the repo .gitignore entry.
echo "*" > "$OUT/.gitignore"
TMP="$OUT/rdocs.db.tmp"
rm -f "$TMP"

# Consistent snapshot of the live DB (same approach as deploy.sh's backup).
_try=0
until sqlite3 -cmd ".timeout 60000" "$DB_FILE" ".backup '$TMP'"; do
  _try=$((_try + 1)); [ "$_try" -lt 5 ] || { log "snapshot failed"; exit 1; }
  log "snapshot attempt $_try failed (busy), retrying"; sleep 5
done

# Scrub: everything that is a credential, a capability token, or would make dev
# act on production systems. Users keep their (bcrypt) password hashes so the
# same logins work on dev. VACUUM rewrites the file so deleted rows are gone.
python3 - "$TMP" <<'PY'
import sqlite3, sys
db = sqlite3.connect(sys.argv[1])
cur = db.cursor()
stmts = [
    "DELETE FROM UserCredential",
    "DELETE FROM DocumentEnvVar",
    "UPDATE UserMcpServer SET authToken = NULL",
    "DELETE FROM AgentBrokerKey",
    "DELETE FROM SlackInstallation",
    "DELETE FROM SlackEventClaim",
    "DELETE FROM SelfHostedJob",
    "DELETE FROM ApiToken",
    "DELETE FROM AgentApiChannel",
    "DELETE FROM ShareLink",
    "UPDATE AiRun SET sessionSecret = NULL, sessionEndpoint = NULL, containerId = NULL",
    "UPDATE AiRun SET status = 'FAILED', error = 'dev refresh: run was in flight on prod', finishedAt = CURRENT_TIMESTAMP WHERE status IN ('RUNNING','PENDING')",
    "UPDATE ScheduledTask SET disabledAt = CURRENT_TIMESTAMP WHERE disabledAt IS NULL",
    "UPDATE DurableApp SET enabled = 0, hostname = NULL, hostPort = NULL, containerId = NULL, sessionEndpoint = NULL, sessionSecret = NULL, startedAt = NULL",
    "UPDATE Document SET runnerMode = 'managed'",
]
for s in stmts:
    try:
        cur.execute(s)
    except sqlite3.OperationalError as e:
        print(f"[refresh-dev-data] skip ({e}): {s}", file=sys.stderr)
db.commit()
db.execute("VACUUM")
db.close()
PY
mv -f "$TMP" "$OUT/rdocs.db"
rm -f "$OUT/rdocs.db-journal"
log "wrote $OUT/rdocs.db ($(du -h "$OUT/rdocs.db" | cut -f1))"

# Dev env: generated once. Random keys, dev URL, in-container DB path, no Slack
# (dev must never answer real channels), no host provider/GitHub credentials.
if [ ! -f "$OUT/.env" ]; then
  rand() { openssl rand -hex 32; }
  cat > "$OUT/.env" <<ENV
# Generated by deploy/refresh-dev-data.sh — dev instance inside the durable container.
APP_URL=https://dev.nielsrolf.com
DATABASE_URL=file:/workspace/dev-data/rdocs.db
SESSION_SECRET=$(rand)
CREDENTIAL_ENCRYPTION_KEY=$(rand)
DEPLOY_SECRET=$(rand)
INTEGRATION_SIGNIN_SECRET=$(rand)
NEXT_SERVER_ACTIONS_ENCRYPTION_KEY=$(openssl rand -base64 32)
NEXT_SKIP_FILE_TRACE=${NEXT_SKIP_FILE_TRACE:-1}
# Agents in dev run in-process inside the (already sandboxed) durable container.
# Container mode would need the 3.6 GB agent image built inside the inner
# dockerd (raise AGENT_INNER_DOCKER_TMPFS_SIZE on the durable container first).
AGENT_RUNNER_MODE=inprocess
AGENT_DETACHED_CONTAINERS=0
AGENT_CREDENTIAL_BROKER=0
DURABLE_APP_ALLOWED_EMAILS=
ENV
  chmod 600 "$OUT/.env"
  log "generated $OUT/.env"
fi
log "done"
